baseURL = "/"
languageCode = "en-us"
title = "Dr Adrian"
theme = "dradriancom"

FootnoteReturnLinkContents = "↑"


[markup]
  [markup.highlight]
    style = "monokailight"

[markup.goldmark.renderer]
unsafe= true